import { makeStyles } from "@material-ui/core";

export const useStyles = makeStyles((theme) => ({
  root: {
    height: "100vh",
    display: "flex",
    flexDirection: "column",
  },

  background: {
    background: "6069BE",
  },

  booklistBox: {
    width: 500,
    height: 200,
  },

  main: {
    flex: 1,
    overflow: "auto",
    flexDirection: "column",
    display: "flex",
    color: "#ffffff",
  },
  title: {
    marginTop: 10,
    marginBottom: 100,
    width: 500,
    height: 200,
  },
  TitleMessage: {
    fontFamily: "'Noto Sans'",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "110px",
    color: "#FFFFFF",
    textShadow: "0 16px 40px rgba(0, 0, 0, 0.25), 0 16px 40px #6068BE",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  subTitleMessage: {
    fontFamily: "'Noto Sans'",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "50px",
    color: "#FFFFFF",
    textShadow: "0 16px 40px rgba(0, 0, 0, 0.25), 0 16px 40px #6068BE",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    marginTop: 100,
    marginBottom: 100,
  },
  ment: {
    width: 1100,
    height: 300,
  },

  center: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    backgroundColor: "rgba(15, 29, 160, 0.65)",
  },

  largeLogo: {
    position: "relative",
    width: 983,
    marginTop: 100,
  },

  MainButton: {
    position: "relative",
    height: 500,
    width: 500,
    margin: 25,
  },

  SignupButton: {
    height: 300,
    width: 550,
  },

  HomeButton: {
    position: "relative",
    height: 300,
    width: 300,
  },

  TitleButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 150,
    marginRight: 150,
    height: 150,
    width: 150,
  },
  footer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  Header: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    paddingTop: 150,
  },
  padding: {
    paddingTop: 190,
    paddingBottom: 190,
  },
  searchResult: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    paddingTop: 150,
    paddingBottom: 150,
  },
  MiniButton: {
    position: "relative",
    height: 300,
    width: 320,
    margin: 20,
  },
  AcceptButton: {
    position: "relative",
    height: 222,
    width: 588,
    margin: 65,
  },
  cards: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  detailUpper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 50,
    marginRight: 50,
    margin: 110,
  },
  detailUpperButton: {
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 100,
    marginTop: -100,
  },
  detailBorrowStatus: {
    marginLeft: 10,
    marginRight: 10,
  },
  RelatedBooks: {
    backgroundColor: "#223069",
    padding: 100,
    justifyContent: "center",
  },
  RelatedBookList: {
    marginLeft: 30,
    marginRight: 30,
  },
  horizontalScroll: {
    display: "flex",
    overflow: "auto",
    whiteSpace: "nowrap",
  },
  AcceptButtonText: {
    position: "absolute",
    top: "50 %",
    left: "150 %",
    transform: "translate(-50 %, -50 %)",
    zIndex: "1",
    fontFamily: "Noto Sans",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "130px",
    lineHeight: "177px",
    display: "flex",
    color: "#6069BE",
  },
  wrapper: {
    display: "flex",
    overflow: "auto",
    whiteSpace: "nowrap",
    width: 1300,
    height: 700,
    background: "#223069",
    boxShadow:
      "inset 4px 16px 40px rgba(0, 0, 0, 0.5), inset 0px 4px 4px rgba(0, 0, 0, 0.25)",
  },
  wrapperSearch: {
    overflow: "scroll",
    width: 1300,
    height: 1600,
    background: "#223069",
    boxShadow:
      "inset 4px 16px 40px rgba(0, 0, 0, 0.5), inset 0px 4px 4px rgba(0, 0, 0, 0.25)",
  },
  outerWrapper: {
    verticalAlign: "middle",
    display: "grid",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  outerWrapperSearch: {
    verticalAlign: "middle",
    display: "grid",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  keyboard: {
    marginTop: 130,
  },
  modal: {
    display: "flex",
    width: 1376,
    height: 1280,
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    bgcolor: "background.paper",
    border: "2px solid #000",
    boxShadow: 24,
    p: 4,
  },
  star: {
    width: 300,
    height: 60,
  },
  MainButtons: {
    gridTemplateColumns: "1fr 1fr",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  Bigcard: {
    verticalAlign: "middle",
    display: "grid",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    width: "100%",
    flexDirection: "column",
  },
  BigcardInner: {
    height: 1800,
    background:
      "linear-gradient(180deg, #353F6B 0%, #353F6B 0.01%, #223069 100%)",
    borderRadius: "60px",
    width: "1300px",
    justifyContent: "center",
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
  },
  Card: {
    background: "#FFFFFF",
    boxShadow: "20px 60px 40px rgba(0, 0, 0, 0.25)",
    borderRadius: "90px",
    justifyContent: "center",
    display: "flex",
    alignItems: "center",
    flexDirection: "column",

    width: 1100,
    height: 1300,

    fontFamily: "'Noto Sans'",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "50px",
    color: "#233173",
  },
  CardFont: {},
  RecommendBtn: {
    background:
      "linear-gradient(180deg, #353F6B 0%, #353F6B 0.01%, #223069 100%)",
    borderRadius: "60px",
    padding: 10,
    height: 750,
    width: 500,
    alignItems: "center",
    justifyContent: "center",
  },
}));
